version: '3.9'
services:
  ui:
    image: node:lts-alpine
    command: sh -c "npm install && npm run start"
    working_dir: /ui
    volumes:
      - nodemodules:/ui/node_modules
      - ./ui:/ui
    ports:
      - 3020:3000
volumes:
  nodemodules:
