create_api:
	npm init -y
	npm install typescript ts-node
	npm install --save express body-parser nodemon
	npm install --save axios compression dotenv helmet morgan uuid winston
	npm install --save express-openapi-validator swagger-ui-express yamljs
	npm install --save-dev eslint eslint-config-airbnb-typescript eslint-plugin-import 
	npm install --save-dev @types/yamljs @types/swagger-ui-express
	npm install --save-dev @typescript-eslint/eslint-plugin @typescript-eslint/parser
	npm install --save-dev @types/compression @types/express @types/helmet
	npm install --save-dev @types/morgan @types/node @types/uuid

